settings:
  name: Setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: Setup and administration docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Limitations
          url: /reference-limitations.html
    - title: Get started
      entries:
        - title: Learn the basics
          entries: 
            - title: BlueXP overview
              url: /concept-overview.html
            - title: Accounts
              url: /concept-netapp-accounts.html
            - title: Connectors
              url: /concept-connectors.html
            - title: Deployment modes
              url: /concept-modes.html
        - title: Get started with standard mode
          entries:
            - title: Quick start
              url: /task-quick-start-standard-mode.html
            - title: Prepare networking
              url: /reference-networking-saas-console.html
            - title: Sign up to BlueXP
              url: /task-sign-up-saas.html
            - title: Log in to BlueXP
              url: /task-logging-in.html
            - title: Create a Connector
              entries:
                - title: AWS
                  entries:
                    - title: Installation options
                      url: /concept-install-options-aws.html
                    - title: Create from BlueXP
                      url: /task-install-connector-aws-bluexp.html
                    - title: Create from the marketplace
                      url: /task-install-connector-aws-marketplace.html
                    - title: Install manually
                      url: /task-install-connector-aws-manual.html
                - title: Azure
                  entries:
                    - title: Installation options
                      url: /concept-install-options-azure.html
                    - title: Create from BlueXP
                      url: /task-install-connector-azure-bluexp.html
                    - title: Create from the marketplace
                      url: /task-install-connector-azure-marketplace.html
                    - title: Install manually
                      url: /task-install-connector-azure-manual.html
                - title: Google Cloud
                  entries:
                    - title: Installation options
                      url: /concept-install-options-google.html
                    - title: Create from BlueXP or using gcloud
                      url: /task-install-connector-google-bluexp.html
                    - title: Install manually
                      url: /task-install-connector-google-manual.html
                - title: On premises
                  url: /task-install-connector-on-prem.html
            - title: Subscribe to BlueXP
              url: /task-subscribe-standard-mode.html
            - title: What you can do next
              url: /reference-whats-next.html
        - title: Get started with restricted mode
          entries:
            - title: Quick start
              url: /task-quick-start-restricted-mode.html
            - title: Prepare for deployment
              url: /task-prepare-restricted-mode.html
            - title: Deploy the Connector
              url: /task-install-restricted-mode.html
            - title: Log in to BlueXP
              url: /task-log-in-restricted-mode.html
            - title: Subscribe to BlueXP
              url: /task-subscribe-restricted-mode.html
            - title: What you can do next
              url: /reference-whats-next-restricted-mode.html
        - title: Get started with private mode
          entries:
            - title: Quick start
              url: /task-quick-start-private-mode.html
            - title: Prepare for deployment
              url: /task-prepare-private-mode.html
            - title: Deploy the Connector
              url: /task-install-private-mode.html
            - title: Log in to BlueXP
              url: /task-log-in-private-mode.html
            - title: What you can do next
              url: /reference-whats-next-private-mode.html
    - title: Administer BlueXP
      entries:
        - title: Identity federation
          url: /concept-federation.html
        - title: BlueXP accounts
          entries:
            - title: Manage your account
              url: /task-managing-netapp-accounts.html
            - title: Monitor operations in your account
              url: /task-monitor-cm-operations.html
            - title: Create another account
              url: /task-create-account.html
            - title: User roles
              url: /reference-user-roles.html
        - title: Connectors
          entries:
            - title: Find the system ID for a Connector
              url: /task-finding-system-id.html
            - title: Manage existing Connectors
              url: /task-managing-connectors.html
            - title: Install an HTTPS certificate
              url: /task-installing-https-cert.html
            - title: Configure proxy settings
              url: /task-configuring-proxy.html
            - title: Default configuration
              url: /reference-connector-default-config.html
        - title: Credentials
          entries:
            - title: Manage AWS credentials
              entries:
                - title: Overview
                  url: /concept-accounts-aws.html
                - title: Manage credentials and subscriptions
                  url: /task-adding-aws-accounts.html
            - title: Manage Azure credentials
              entries:
                - title: Overview
                  url: /concept-accounts-azure.html
                - title: Manage credentials and subscriptions
                  url: /task-adding-azure-accounts.html
            - title: Manage Google Cloud credentials
              entries:
                - title: Overview
                  url: /concept-accounts-gcp.html
                - title: Manage credentials and subscriptions
                  url: /task-adding-gcp-accounts.html
            - title: Manage NSS credentials associated with a BlueXP account
              url: /task-adding-nss-accounts.html
            - title: Manage credentials associated with your BlueXP login
              url: /task-manage-user-credentials.html
        - title: Discovered cloud storage
          entries:
            - title: Manage your Amazon S3 buckets
              url: /task-viewing-amazon-s3.html
            - title: Manage your Azure Blob accounts
              url: /task-viewing-azure-blob.html
            - title: Manage your Google Cloud Storage buckets
              url: /task-viewing-gcp-storage.html
    - title: Reference
      entries:
        - title: Permissions
          entries:
            - title: Permissions summary
              url: /reference-permissions.html
            - title: AWS permissions for the Connector
              url: /reference-permissions-aws.html
            - title: Azure permissions for the Connector
              url: /reference-permissions-azure.html
            - title: Google Cloud permissions for the Connector
              url: /reference-permissions-gcp.html
        - title: Ports
          entries:
            - title: Security group rules in AWS
              url: /reference-ports-aws.html
            - title: Security group rules in Azure
              url: /reference-ports-azure.html
            - title: Firewall rules in Google Cloud
              url: /reference-ports-gcp.html
            - title: Ports for the on-prem Connector
              url: /reference-ports-on-prem.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: All BlueXP documentation
homepage:
  tiles:
    - title: Get started
      links:
        - title: Learn about BlueXP
          url: concept-overview.html
        - title: Learn about deployment modes
          url: concept-modes.html
        - title: Get started with standard mode
          url: /task-quick-start-standard-mode.html
        - title: Get started with restricted mode
          url: /task-quick-start-restricted-mode.html
        - title: Get started with private mode
          url: /task-quick-start-private-mode.html
    - title: BlueXP accounts
      links:
        - title: Learn about BlueXP accounts
          url: concept-netapp-accounts.html
        - title: Manage your BlueXP account
          url: task-managing-netapp-accounts.html
        - title: Monitor operations in your account
          url: task-monitor-cm-operations.html
    - title: Connectors
      links:
        - title: Learn about Connectors
          url: concept-connectors.html
        - title: Create a Connector in AWS (standard mode)
          url: task-quick-start-connector-aws.html
        - title: Create a Connector in Azure (standard mode)
          url: task-quick-start-connector-azure.html
        - title: Create a Connector in Google Cloud (standard mode)
          url: task-quick-start-connector-google.html
        - title: Create a Connector on premises (standard mode)
          url: task-quick-start-connector-on-prem.html
        - title: Manage Connectors
          url: task-managing-connectors.html
    - title: Permissions
      links:
        - title: Permissions summary
          url: reference-permissions.html
        - title: AWS permissions for the Connector
          url: reference-permissions-aws.html
        - title: Azure permissions for the Connector
          url: reference-permissions-azure.html
        - title: Google Cloud permissions for the Connector
          url: reference-permissions-gcp.html      
    - title: Credentials
      links:
        - title: Manage AWS credentials
          url: task-adding-aws-accounts.html
        - title: Manage Azure credentials
          url: task-adding-azure-accounts.html
        - title: Manage Google Cloud credentials
          url: task-adding-gcp-accounts.html
        - title: Manage NSS credentials for your account
          url: task-adding-nss-accounts.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: BlueXP blog
          url: https://bluexp.netapp.com/blog
        - title: Cloud webinars
          url: https://bluexp.netapp.com/events