---
sidebar: sidebar
permalink: reference-networking-saas-console.html
keywords: networking, urls, endpoints, web browser, console, network, set up networking
summary: When getting started with BlueXP, ensure that your networking allows access to specific endpoints from the BlueXP console. Depending on how you plan to use BlueXP, you might also need to set up networking for a Connector and for specific BlueXP services.
---

= Prepare your networking
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When getting started with BlueXP, ensure that your networking allows access to specific endpoints from the BlueXP console. Depending on how you plan to use BlueXP, you might also need to set up networking for a Connector and for specific BlueXP services.

== Prepare networking for user access to the BlueXP console

As you use the BlueXP web-based console that's provided through the SaaS layer, it contacts several endpoints to complete data management tasks. The machine running the web browser must have connections to these endpoints.

[cols=2*,options="header,autowidth"]
|===
| Endpoints
| Purpose

| 
\https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com  

| Your web browser contacts these URLs when you use the BlueXP web-based console.

a|
AWS services (amazonaws.com):

* CloudFormation
* Elastic Compute Cloud (EC2)
* Key Management Service (KMS)
* Security Token Service (STS)
* Simple Storage Service (S3)

| Required to deploy a Connector from BlueXP in AWS. The exact endpoint depends on the region in which you deploy the Connector. https://docs.aws.amazon.com/general/latest/gr/rande.html[Refer to AWS documentation for details.^]

|
\https://management.azure.com

\https://login.microsoftonline.com

| Required to deploy a Connector from BlueXP in most Azure regions.

|
\https://management.microsoftazure.de

\https://login.microsoftonline.de
| Required to deploy a Connector from BlueXP in Azure Germany regions.

|
\https://management.usgovcloudapi.net

\https://login.microsoftonline.com

| Required to deploy a Connector from BlueXP in Azure US Gov regions.

|
\https://www.googleapis.com

| Required to deploy a Connector from BlueXP in Google Cloud.

| \https://signin.b2c.netapp.com
| Required to update NetApp Support Site (NSS) credentials or to add new NSS credentials to BlueXP.

|
\https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com
| Your web browser connects to these endpoints for centralized user authentication through BlueXP.

| \https://widget.intercom.io
| For in-product chat that enables you to talk to NetApp cloud experts.

|===

Beyond these endpoints, you also need to ensure that the Connector has outbound internet access to contact specific endpoints for day-to-day operations. You can find the list of these endpoints by following the links in the next section below.

== Prepare networking for a Connector

How you prepare your networking for a Connector depends on where you plan to install the Connector, which can be in the cloud or on your premises. For details about Connector networking requirements, refer to the following pages:

* link:task-set-up-networking-aws.html[Set up AWS networking]
* link:task-set-up-networking-azure.html[Set up Azure networking]
* link:task-set-up-networking-google.html[Set up Google Cloud networking]
* link:task-set-up-networking-on-prem.html[Set up on-prem networking]

== Prepare networking for BlueXP services

As you get started with BlueXP, you should ensure that you've met the networking requirements for the BlueXP services that you plan to use. For details, refer to the documentation for each service.

https://docs.netapp.com/us-en/bluexp-family/[BlueXP documentation^]