---
sidebar: sidebar
permalink: task-subscribe-standard-mode.html
keywords: subscribe, subscription, marketplace subscription, paygo, contract, annual contract
summary: Subscribe to BlueXP from your cloud provider's marketplace to pay for BlueXP services at an hourly rate or through an annual contract. If you purchased a license from NetApp, you also need to subscribe to the marketplace offering. Your license is always charged first, but you'll be charged at the hourly rate if you exceed your licensed capacity or if the license's term expires.
---

= Subscribe to BlueXP (standard mode)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
include::_include/subscribe-intro.adoc[]

A marketplace subscription enables charging for the following BlueXP services:

* Backup and recovery
* Classification
* Cloud Volumes ONTAP
* Tiering

.Before you begin

Subscribing to BlueXP involves associating a marketplace subscription with the cloud credentials that are associated with a Connector. If you followed the "Get started with standard mode" workflow, then you should already have a Connector. To learn more, view the link:task-quick-start-standard-mode.html[Quick start for BlueXP in standard mode].

// start tabbed area

[role="tabbed-block"]
====

.AWS
--
include::_include/subscribe-aws.adoc[]
--

.Azure
--
include::_include/subscribe-azure.adoc[]
--

.Google Cloud
--
include::_include/subscribe-google.adoc[]
--

====
// end tabbed area

.Related links

* https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html[Manage BYOL capacity-based licenses for Cloud Volumes ONTAP^]
* https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html[Manage BYOL licenses for BlueXP data services^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-aws-accounts.html[Manage AWS credentials and subscriptions for BlueXP]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-azure-accounts.html[Manage Azure credentials and subscriptions for BlueXP]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-gcp-accounts.html[Manage Google Cloud credentials and subscriptions for BlueXP]

== Videos

video::aa562370-b58d-41d0-8c61-b05100ffe66a[panopto, title="Subscribe to BlueXP from the AWS Marketplace"]

video::b7e97509-2ecf-4fa0-b39b-b0510109a318[panopto, title="Subscribe to BlueXP from the Azure Marketplace"]