---
sidebar: sidebar
permalink: task-install-connector-aws-marketplace.html
keywords: install connector, aws connector installation, aws connector, install connector in aws, bluexp, aws marketplace, manual install, create connector
summary: Create a Connector directly from the BlueXP web-based console, from the AWS Marketplace, or by installing the software on your own Linux host.
---

= Create a Connector from the AWS Marketplace
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
To create a Connector in Azure from BlueXP, you need to set up your networking, prepare Azure permissions, and then create the Connector.

== Step 1: Set up AWS networking

Set up your networking so the Connector can manage resources and processes within your hybrid cloud environment. For example, you need to ensure that connections are available to target networks and that outbound internet access is available.

VPC and subnet::
When you create the Connector, you need to specify the VPC and subnet where the Connector should reside.

Connections to target networks::
A Connector requires a network connection to the location where you're planning to create and manage working environments.

Outbound internet access::
The network location where you deploy the Connector must have an outbound internet connection. Outbound internet access is also required from your web browser when deploying the Connector from the BlueXP console.

Endpoints contacted from the BlueXP console::
As you use the BlueXP web-based console that's provided through the SaaS layer, it contacts several endpoints to complete data management tasks. This includes endpoints that are contacted to deploy the Connector from the BlueXP console.
+
link:reference-networking-saas-console.html[View the list of endpoints contacted from the BlueXP console].

Endpoints contacted during manual installation::

include::_include/endpoints-manual-install.adoc[tag=endpoint-list]

include::_include/endpoints-manual-install.adoc[tag=update]

Endpoints contacted from the Connector::
The Connector requires outbound internet access to contact the following endpoints in order to manage resources and processes within your public cloud environment for day-to-day operations.

[cols="2a,1a",options="header,autowidth"]
|===
| Endpoints
| Purpose

include::_include/endpoints-connector.adoc[tag=aws-endpoints]

include::_include/endpoints-connector.adoc[tag=nss-endpoints]

include::_include/endpoints-connector.adoc[tag=saas-endpoints]

include::_include/endpoints-connector.adoc[tag=upgrade-endpoints]

|===

Proxy server::

include::_include/proxy-server.adoc[]

Ports::

include::_include/ports.adoc[]

IP address limitation::

include::_include/ip-limitation.adoc[]

== Step 2: Set up AWS permissions

To prepare for a marketplace deployment, create IAM policies in AWS and attach them to an IAM role. When you create the Connector from the AWS Marketplace, you'll be prompted to select that IAM role.

.Steps

include::_include/aws-permissions.adoc[tag=policy]
+
Depending on the BlueXP services that you're planning to use, you might need to create a second policy. For standard regions, the permissions are spread across two policies. Two policies are required due to a maximum character size limit for managed policies in AWS. link:reference-permissions-aws.html[Learn more about IAM policies for the Connector].

include::_include/aws-permissions.adoc[tag=role]

.Result

You now have an IAM role that you can associate with the EC2 instance during deployment from the AWS Marketplace.

== Step 3: Install the Connector

Create a Connector directly from the BlueXP web-based console.

.Before you begin

You should have the following:

* A VPC and subnet that meets networking requirements.
+
link:task-set-up-networking-aws.html[Learn about networking requirements].

* An IAM role with an attached policy that includes the required permissions for the Connector.
+
link:task-set-up-permissions-aws.html[Learn how to set up AWS permissions].

* Permissions to subscribe and unsubscribe from the AWS Marketplace for your IAM user.

* An understanding of CPU and RAM requirements for the instance.
+
link:reference-host-requirements-aws.html[Review instance requirements].

* A key pair for the EC2 instance.

include::_include/aws-marketplace.adoc[]

+
AWS launches the software with the specified settings. The Connector instance and software should be running in approximately five minutes.

. Open a web browser from a host that has a connection to the Connector virtual machine and enter the following URL:
+
https://_ipaddress_

. After you log in, set up the Connector:
.. Specify the BlueXP account to associate with the Connector.
.. Enter a name for the system.
.. Under *Are you running in a secured environment?* keep restricted mode disabled.
+
You should keep restricted mode disabled because these steps describe how to use BlueXP in standard mode. You should enable restricted mode only if you have a secure environment and want to disconnect this account from BlueXP backend services. If that's the case, link:task-quick-start-restricted-mode.html[follow steps to get started with BlueXP in restricted mode].
.. Select *Let's start*.

.Result

The Connector is now installed and set up with your BlueXP account.

Open a web browser and go to the https://console.bluexp.netapp.com[BlueXP console^] to start using the Connector with BlueXP.