---
sidebar: sidebar
permalink: task-set-up-permissions-aws.html
keywords: aws permissions, set up permissions, set up aws permissions, permissions, iam role, iam policy, json, policy, role, credentials
summary: Set up permissions in AWS so that you can deploy the Connector with the permissions that it needs to manage your data and storage infrastructure. How you set up and provide the permissions depends on the installation option that you're planning to use.
---

= Set up AWS permissions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Set up permissions in AWS so that you can deploy the Connector with the permissions that it needs to manage your data and storage infrastructure. How you set up and provide the permissions depends on the installation option that you're planning to use.

You can choose from the following installation options:

* *Install from BlueXP*: Set up permissions that enable BlueXP to authenticate with AWS and deploy the instance. BlueXP automatically sets up permissions for the Connector instance during deployment.
+
<<Set up permissions to create the Connector from BlueXP,View step-by-step instructions>>.

* *Install from the AWS Marketplace*: Set up an IAM role that you can associate with the Connector instance.
+
<<Set up permissions for the Connector when deploying from the AWS Marketplace,View step-by-step instructions>>.

* *Manual install*: Create IAM policies and attach them to an IAM role or to an IAM user.
+
<<Set up permissions to assign after manual installation,View step-by-step instructions>>.

== Set up permissions to create the Connector from BlueXP

BlueXP needs to authenticate with AWS before it can deploy the Connector instance in your VPC. You can choose one of these authentication methods:

* Let BlueXP assume an IAM role that has the required permissions
* Provide an AWS access key and secret key for an IAM user who has the required permissions

With either option, the first step is to create an IAM policy. This policy contains only the permissions needed to launch the Connector instance in AWS from BlueXP.

If needed, you can restrict the IAM policy by using the IAM `Condition` element. https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition.html[AWS documentation: Condition element^]

TIP: When BlueXP creates the Connector, it applies a new set of permissions to the Connector instance that enables the Connector to manage AWS resources.

.Steps

. Go to the AWS IAM console.

. Select *Policies > Create policy*.

. Select *JSON*.

. Copy and paste the following policy:
+
As a reminder, this policy contains only the permissions needed to launch the Connector instance in AWS from BlueXP. link:reference-permissions-aws.html[View permissions required for the Connector instance itself].
+
[source,json]
{
    "Version": "2012-10-17",
    "Statement": [{
            "Effect": "Allow",
            "Action": [
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:PutRolePolicy",
                "iam:CreateInstanceProfile",
                "iam:DeleteRolePolicy",
                "iam:AddRoleToInstanceProfile",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:DeleteInstanceProfile",
                "iam:PassRole",
                "ec2:DescribeInstanceStatus",
                "ec2:RunInstances",
                "ec2:ModifyInstanceAttribute",
                "ec2:CreateSecurityGroup",
                "ec2:DeleteSecurityGroup",
                "ec2:DescribeSecurityGroups",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface",
                "ec2:ModifyNetworkInterfaceAttribute",
                "ec2:DescribeSubnets",
                "ec2:DescribeVpcs",
                "ec2:DescribeDhcpOptions",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeRegions",
                "ec2:DescribeInstances",
                "ec2:CreateTags",
                "ec2:DescribeImages",
                "cloudformation:CreateStack",
                "cloudformation:DeleteStack",
                "cloudformation:DescribeStacks",
                "cloudformation:DescribeStackEvents",
                "cloudformation:ValidateTemplate",
                "ec2:AssociateIamInstanceProfile",
                "ec2:DescribeIamInstanceProfileAssociations",
                "ec2:DisassociateIamInstanceProfile",
                "iam:GetRole",
                "iam:TagRole",
                "iam:ListRoles",
                "kms:ListAliases"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:TerminateInstances"
            ],
            "Condition": {
                "StringLike": {
                    "ec2:ResourceTag/OCCMInstance": "*"
                }
            },
            "Resource": [
                "arn:aws:ec2:*:*:instance/*"
            ]
        }
    ]
}

. Select *Next* and add tags, if needed.

. Select *Next* and enter a name and description.

. Select *Create policy*.

. Either attach the policy to an IAM role that BlueXP can assume or to an IAM user so that you can provide BlueXP with access keys:

* (Option 1) Set up an IAM role that BlueXP can assume:
+
.. Go to the AWS IAM console in the target account.

.. Under Access Management, select *Roles > Create Role* and follow the steps to create the role.

.. Under *Trusted entity type*, select *AWS account*.

.. Select *Another AWS account* and enter the ID of the BlueXP SaaS account: 952013314444

.. Select the policy that you created in the previous section.

.. After you create the role, copy the Role ARN so that you can paste it in BlueXP when you create the Connector.

* (Option 2) Set up permissions for an IAM user so that you can provide BlueXP with access keys:
+
.. From the AWS IAM console, select *Users* and then select the user name.

.. Select *Add permissions > Attach existing policies directly*.

.. Select the policy that you created.

.. Select *Next* and then select *Add permissions*.

.. Ensure that you have the access key and secret key for the IAM user.

.Result

You should now have an IAM role that has the required permissions or an IAM user that has the required permissions. When you create the Connector from BlueXP, you can provide information about the role or access keys.

== Set up permissions for the Connector when deploying from the AWS Marketplace

To prepare for a marketplace deployment, create IAM policies in AWS and attach them to an IAM role. When you create the Connector from the AWS Marketplace, you'll be prompted to select that IAM role.

.Steps

include::_include/aws-permissions.adoc[tag=policy]
+
Depending on the BlueXP services that you're planning to use, you might need to create a second policy. For standard regions, the permissions are spread across two policies. Two policies are required due to a maximum character size limit for managed policies in AWS. link:reference-permissions-aws.html[Learn more about IAM policies for the Connector].

include::_include/aws-permissions.adoc[tag=role]

.Result

You now have an IAM role that you can associate with the EC2 instance during deployment from the AWS Marketplace.

== Set up permissions to assign after manual installation

If you're planning to manually install the Connector software on your own Linux host in AWS, you can provide permissions in the following ways:

* Option 1: Create IAM policies and attach the policies to an IAM role that you can associate with the EC2 instance.
* Option 2: Provide BlueXP with AWS access keys for an IAM user who has the required permissions.

// start tabbed area

[role="tabbed-block"]
====

.IAM role
--

.Steps

include::_include/aws-permissions.adoc[tag=policy]
+
Depending on the BlueXP services that you're planning to use, you might need to create a second policy. For standard regions, the permissions are spread across two policies. Two policies are required due to a maximum character size limit for managed policies in AWS. link:reference-permissions-aws.html[Learn more about IAM policies for the Connector].

include::_include/aws-permissions.adoc[tag=role]

.Result

You now have an IAM role that you can associate with the EC2 instance after you install the Connector. link:task-provide-permissions-aws.html[Learn how to provide these permissions to BlueXP].
--

.AWS access key
--

.Steps

include::_include/aws-permissions.adoc[tag=policy]
+
Depending on the BlueXP services that you're planning to use, you might need to create a second policy.
+
For standard regions, the permissions are spread across two policies. Two policies are required due to a maximum character size limit for managed policies in AWS. link:reference-permissions-aws.html[Learn more about IAM policies for the Connector].

include::_include/aws-permissions.adoc[tag=keys]

.Result

You now have an IAM user that has the required permissions and an access key that you can provide to BlueXP. link:task-provide-permissions-aws.html[Learn how to provide these permissions to BlueXP].
--

====
// end tabbed area