---
sidebar: sidebar
permalink: task-provide-permissions-on-prem.html
keywords: permissins, on prem permissions, aws permissions, azure permissions, credentials, aws credentials, azure credentials
summary: After you install and set up the Connector, you need to add your cloud credentials so that BlueXP has the required permissions to perform actions in AWS or Azure.
---

= Provide permissions to BlueXP for on-prem installs
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After you install and set up the Connector, you need to add your cloud credentials so that BlueXP has the required permissions to perform actions in AWS or Azure.

TIP: Why not Google Cloud? When the Connector is installed on your premises, it can't manage your resources in Google Cloud. The Connector must be installed in Google Cloud to manage any resources that resides there.

// start tabbed area

[role="tabbed-block"]
====

.AWS
--
.Before you begin

If you just created these credentials in AWS, it might take a few minutes until they are available for use. Wait a few minutes before you add the credentials to BlueXP.

.Steps

include::_include/provide-permissions-access-key.adoc[]

You can now go to the https://console.bluexp.netapp.com[BlueXP console^] to start using the Connector with BlueXP.
--

.Azure
--

.Before you begin

If you just created these credentials in Azure, it might take a few minutes until they are available for use. Wait a few minutes before you add the credentials to BlueXP.

.Steps

include::_include/azure-provide-permissions-service-principal.adoc[]

.Result

BlueXP now has the permissions that it needs to perform actions in Azure on your behalf. You can now go to the https://console.bluexp.netapp.com[BlueXP console^] to start using the Connector with BlueXP.
--

====

// end tabbed area