---
sidebar: sidebar
permalink: task-provide-permissions-aws.html
keywords: aws permissions, set up aws permissions, iam role, json policy, bluexp policy, aws marketplace, aws access key, access key, iam policy, permissions
summary: If you manually installed the Connector software on your own Linux host, you need to provide BlueXP with the permissions that you previously set up. Providing the permissions enables BlueXP to manage your data and storage infrastructure in AWS.
---

= Provide AWS permissions to BlueXP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If you manually installed the Connector software on your own Linux host, you need to provide BlueXP with the permissions that you previously set up. Providing the permissions enables BlueXP to manage your data and storage infrastructure in AWS.

link:task-set-up-permissions-aws.html[Learn how to set up these permissions].

These steps don't apply if you deployed the Connector directly from BlueXP or from the AWS Marketplace because the required permissions were provided during deployment.

// start tabbed area

[role="tabbed-block"]
====

.IAM role
--
Attach the IAM role that you previously created to the Connector EC2 instance.

include::_include/provide-permissions-iam-role.adoc[]

Go to the https://console.bluexp.netapp.com[BlueXP console^] to start using the Connector with BlueXP.
--

.AWS access key
--
Provide BlueXP with the AWS access key for an IAM user that has the required permissions.

.Steps

. Ensure that the correct Connector is currently selected in BlueXP.

include::_include/provide-permissions-access-key.adoc[]

Go to the https://console.bluexp.netapp.com[BlueXP console^] to start using the Connector with BlueXP.
--

====
// end tabbed area