---
sidebar: sidebar
permalink: task-install-connector-google-manual.html
keywords: install connector, google cloud connector installation, google cloud connector, install connector in google cloud, bluexp, gcloud, manual install, create connector, gcp installation, gcp connector
summary: Create a Connector directly from the BlueXP web-based console, by using gcloud, or by installing the software on your own Linux host.
---

= Create a Connector in Google Cloud
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Words

== Step 1: Review host requirements

The Connector software must run on a host that meets specific operating system requirements, RAM requirements, port requirements, and so on. If you plan to manually install the Connector, you should ensure that your host meets these requirements.

When you deploy the Connector from BlueXP or by using glcoud, the image includes the required OS and software components.

include::_include/os-reqs.adoc[tag=start]

include::_include/os-reqs.adoc[tag=google-machine]

include::_include/os-reqs.adoc[tag=end]

== Step 2: Set up networking

Set up your networking so the Connector can manage resources and processes within your hybrid cloud environment. For example, you need to ensure that connections are available to target networks and that outbound internet access is available.

VPC and subnet:: 

When you create the Connector, you need to specify the VPC and subnet where the Connector should reside.

Connections to target networks::

A Connector requires a network connection to the location where you're planning to create and manage working environments.

Outbound internet access::

The network location where you deploy the Connector must have an outbound internet connection. Outbound internet access is also required from your web browser when deploying the Connector from the BlueXP console.

Endpoints contacted from the BlueXP console::

As you use the BlueXP web-based console that's provided through the SaaS layer, it contacts several endpoints to complete data management tasks. This includes endpoints that are contacted to deploy the Connector from the BlueXP console.
+
link:reference-networking-saas-console.html[View the list of endpoints contacted from the BlueXP console].

Endpoints contacted during manual installation::

include::_include/endpoints-manual-install.adoc[tag=endpoint-list]

include::_include/endpoints-manual-install.adoc[tag=update]

Endpoints contacted from the Connector::

The Connector requires outbound internet access to contact the following endpoints in order to manage resources and processes within your public cloud environment for day-to-day operations.

[cols="2a,1a",options="header,autowidth"]
|===
| Endpoints
| Purpose

include::_include/endpoints-connector.adoc[tag=google-cloud-endpoints]

include::_include/endpoints-connector.adoc[tag=nss-endpoints]

include::_include/endpoints-connector.adoc[tag=saas-endpoints]

include::_include/endpoints-connector.adoc[tag=upgrade-endpoints]

|===

Proxy server::

include::_include/proxy-server.adoc[]

Ports::

include::_include/ports.adoc[]

IP address limitation::

include::_include/ip-limitation.adoc[]

== Step 3: Set up Google Cloud permissions

=== Set up permissions for the Connector

A service account is required to provide the Connector with the permissions that BlueXP needs to manage resources in Google Cloud. You need to associate this service account with the Connector VM.

.Steps

. Create a custom role in Google Cloud:

.. Create a YAML file that includes the contents of the link:reference-permissions-gcp.html[service account permissions for the Connector].

.. From Google Cloud, activate cloud shell.

.. Upload the YAML file that includes the required permissions.

.. Create a custom role by using the `gcloud iam roles create` command.
+
The following example creates a role named "connector" at the project level:
+
`gcloud iam roles create connector --project=myproject --file=connector.yaml`
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud[Google Cloud docs: Creating and managing custom roles^]

. Create a service account in Google Cloud:

.. From the IAM & Admin service, select *Service Accounts > Create Service Account*.

.. Enter service account details and select *Create and Continue*.

.. Select the role that you just created.

.. Finish the remaining steps to create the role.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account[Google Cloud docs: Creating a service account^]

.Result

The service account for the Connector VM is set up.

=== Set up permissions across projects

If you plan to deploy Cloud Volumes ONTAP systems in different projects than the project where the Connector resides, then you'll need to provide the Connector's service account with access to those projects.

For example, let's say the Connector is in project 1 and you want to create Cloud Volumes ONTAP systems in project 2. You'll need to grant access to the service account in project 2.

.Steps

. In the Google Cloud console, go to the IAM service and select the project where you want to create Cloud Volumes ONTAP systems.

. On the *IAM* page, select *Grant Access* and provide the required details.
+
* Enter the email of the Connector's service account.
* Select the Connector's custom role.
* Select *Save*.

For more details, refer to https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role[Google Cloud documentation^]

=== Set up shared VPC permissions

If you are using a shared VPC to deploy resources into a service project, then you'll need to prepare your permissions. 

This table is for reference and your environment should reflect the permissions table when IAM configuration is complete.

[cols="10,10,10,20,20,30",options="header"]
|===

| Identity
| Creator
| Hosted in
| Service project permissions
| Host project permissions
| Purpose

| Google account to deploy the Connector | Custom | Service Project
a| link:task-set-up-permissions-google.html#set-up-permissions-to-create-the-connector-from-bluexp-or-gcloud[Connector deployment policy]
a| compute.networkUser
| Deploying the Connector in the service project

| Connector service account | Custom | Service project a|
link:reference-permissions-gcp.html[Connector service account policy]
a|
* compute.networkUser
* deploymentmanager.editor
| Deploying and maintaining Cloud Volumes ONTAP and services in the service project

| Cloud Volumes ONTAP service account | Custom | Service project a|
* storage.admin
* member: BlueXP service account as serviceAccount.user
| N/A | (Optional) For data tiering and BlueXP backup and recovery

| Google APIs service agent | Google Cloud | Service project a|
(Default) Editor
a|
compute.networkUser
| Interacts with Google Cloud APIs on behalf of deployment. Allows BlueXP to use the shared network.

| Google Compute Engine default service account | Google Cloud | Service project a|
(Default) Editor
a|
compute.networkUser
| Deploys Google Cloud instances and compute infrastructure on behalf of deployment. Allows BlueXP to use the shared network.

|===

Notes:

. deploymentmanager.editor is only required at the host project if you are not passing firewall rules to the deployment and are choosing to let BlueXP create them for you. BlueXP will create a deployment in the host project which contains the VPC0 firewall rule if no rule is specified.

. firewall.create and firewall.delete are only required if you are not passing firewall rules to the deployment and are choosing to let BlueXP create them for you. These permissions reside in the BlueXP account .yaml file. If you are deploying an HA pair using a shared VPC, these permissions will be used to create the firewall rules for VPC1, 2 and 3. For all other deployments, these permissions will also be used to create rules for VPC0.

. For data tiering, the tiering service account must have the serviceAccount.user role on the service account, not just at the project level. Currently if you assign serviceAccount.user at the project level, the permissions don't show when you query the service account with getIAMPolicy.

== Step 4: Enable Google Cloud APIs

Several Google Cloud APIs must be enabled before you can deploy the Connector and Cloud Volumes ONTAP in Google Cloud.

.Step

. Enable the following Google Cloud APIs in your project:
+
include::_include/google-cloud-apis.adoc[]

https://cloud.google.com/apis/docs/getting-started#enabling_apis[Google Cloud documentation: Enabling APIs^]

== Step 5: Install the Connector

Create a Connector directly from the BlueXP web-based console, by using gcloud, or by installing the software on your own Linux host.

include::_include/manual-install.adoc[tag=before]

include::_include/manual-install.adoc[tag=about]

include::_include/manual-install.adoc[tag=main-steps]

include::_include/manual-install.adoc[tag=standard-mode-steps-for-cloud]

.What's next?

link:task-provide-permissions-google.html[Provide BlueXP with the permissions that you previously setup].

// end tabbed area

== Step 6: Provide Google Cloud permissions to BlueXP

If you manually installed the Connector software on your own Linux host, you need to provide BlueXP with the permissions that you previously set up. Providing the permissions enables BlueXP to manage your data and storage infrastructure in Google Cloud.

link:task-set-up-permissions-google.html[Learn how to set up these permissions].

These steps don't apply if you deployed the Connector directly from BlueXP or by using gcloud.

.Steps

. Go to the Google Cloud portal and assign the service account to the Connector VM instance.
+
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes[Google Cloud documentation: Changing the service account and access scopes for an instance^]

. If you want to manage resources in other Google Cloud projects, grant access by adding the service account with the BlueXP role to that project. You'll need to repeat this step for each project.

.Result

BlueXP now has the permissions that it needs to perform actions in Google Cloud on your behalf.