---
sidebar: sidebar
permalink: task-provide-permissions-azure.html
keywords: azure permissions, connector permissions, custom role, azure custom role, service principal, how to provide azure permissions, set up azure permissions, provide azure permissions, permissions
summary: If you created the Connector from the Azure Marketplace or manually installed the software, you need to provide BlueXP with the permissions that you previously set up. Providing the permissions enables BlueXP to manage your data and storage infrastructure in Azure.
---

= Provide Azure permissions to BlueXP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If you created the Connector from the Azure Marketplace or manually installed the software, you need to provide BlueXP with the permissions that you previously set up. Providing the permissions enables BlueXP to manage your data and storage infrastructure in Azure.

link:task-set-up-permissions-azure.html[Learn how to set up these permissions].

These steps don't apply if you deployed the Connector directly from BlueXP because BlueXP assigns the required permissions during deployment. 

[role="tabbed-block"]
====

.Custom role
--
include::_include/azure-provide-permissions-role.adoc[]

.What's next?

Go to the https://console.bluexp.netapp.com[BlueXP console^] to start using the Connector with BlueXP.
--

.Service principal
--
.Steps

include::_include/azure-provide-permissions-service-principal.adoc[]

.Result

BlueXP now has the permissions that it needs to perform actions in Azure on your behalf.
--

====
// end tabbed area