---
sidebar: sidebar
permalink: task-set-up-networking-on-prem.html
keywords: networking, on prem networking, endpoints, urls, ports, ip address, proxy, proxy server, connections
summary: Set up your networking so the Connector can manage resources and processes within your hybrid cloud environment. For example, you need to ensure that connections are available to target networks and that outbound internet access is available.
---

= Set up on-prem networking
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Set up your networking so the Connector can manage resources and processes within your hybrid cloud environment. For example, you need to ensure that connections are available to target networks and that outbound internet access is available.

== Connections to target networks

A Connector requires a network connection to the type of working environment that you're creating and the services that you're planning to enable.

For example, if you want to launch Cloud Volumes ONTAP in the cloud, then you must set up a VPN connection from your corporate network to the virtual network where you plan to launch Cloud Volumes ONTAP.

== Outbound internet access

The network location where you deploy the Connector must have an outbound internet connection.

=== Endpoints contacted during manual installation

include::_include/endpoints-manual-install.adoc[tag=start]

include::_include/endpoints-manual-install.adoc[tag=update]

=== Endpoints contacted from the Connector

The Connector requires outbound internet access to contact the following endpoints in order to manage resources and processes within your public cloud environment for day-to-day operations.

[cols=2*,options="header,autowidth"]
|===
| Endpoints
| Purpose

a|
AWS services (amazonaws.com):

* CloudFormation
* Elastic Compute Cloud (EC2)
* Identity and Access Management (IAM)
* Key Management Service (KMS)
* Security Token Service (STS)
* Simple Storage Service (S3)

| To manage resources in AWS. The exact endpoint depends on the region in which you deploy the Connector. https://docs.aws.amazon.com/general/latest/gr/rande.html[Refer to AWS documentation for details^]

| 
\https://management.azure.com
\https://login.microsoftonline.com

| To manage resources in Azure public regions.

| 
\https://management.chinacloudapi.cn
\https://login.chinacloudapi.cn

| To manage resources in Azure China regions.

| 
\https://www.googleapis.com/compute/v1/
\https://compute.googleapis.com/compute/v1
\https://cloudresourcemanager.googleapis.com/v1/projects
\https://www.googleapis.com/compute/beta
\https://storage.googleapis.com/storage/v1
\https://www.googleapis.com/storage/v1
\https://iam.googleapis.com/v1
\https://cloudkms.googleapis.com/v1
\https://www.googleapis.com/deploymentmanager/v2/projects

| To manage resources in Google Cloud.

| \https://support.netapp.com | To obtain licensing information and to send AutoSupport messages to NetApp support.

a| 

\https://*.api.bluexp.netapp.com

\https://api.bluexp.netapp.com

\https://*.cloudmanager.cloud.netapp.com

\https://cloudmanager.cloud.netapp.com

a| To provide SaaS features and services within BlueXP.

NOTE: The Connector is currently contacting "cloudmanager.cloud.netapp.com" but it will start contacting "api.bluexp.netapp.com" in an upcoming release.

| \https://cloudmanagerinfraprod.azurecr.io

\https://*.blob.core.windows.net
| To upgrade the Connector and its Docker components.

|===

.Related link

link:reference-networking-saas-console.html[Prepare networking for user access to the BlueXP console]

== Proxy server

include::_include/proxy-server.adoc[]

== Ports

include::_include/ports.adoc[]

== IP address limitation

include::_include/ip-limitation.adoc[]