---
sidebar: sidebar
permalink: task-install-connector-on-prem.html
keywords: install connector, on prem connector installation, on prem connector, install connector on prem, manual install
summary: Install a Connector on premises and then log in and set it up to work with your BlueXP account.
---

= Install and set up a Connector on premises
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Install a Connector on premises and then log in and set it up to work with your BlueXP account.

== Install the Connector

Download and install the Connector software on an existing Linux host on premises.

include::_include/aws-permissions.adoc[tag=before]

include::_include/aws-permissions.adoc[tag=about]

include::_include/aws-permissions.adoc[tag=main-steps]

.Result

The Connector is now installed. At the end of the installation, the Connector service (occm) restarts twice if you specified a proxy server.

== Set up the Connector

Sign up or log in and then set up the Connector to work with your account.

.Steps

. Open a web browser and enter the following URL:
+
https://_ipaddress_
+
_ipaddress_ can be localhost, a private IP address, or a public IP address, depending on the configuration of the host. For example, if the Connector is in the public cloud without a public IP address, you must enter a private IP address from a host that has a connection to the Connector host.

. Sign up or log in.

. After you log in, set up BlueXP:
.. Specify the BlueXP account to associate with the Connector.
.. Enter a name for the system.
.. Under *Are you running in a secured environment?* keep restricted mode disabled.
+
You should keep restricted mode disabled because these steps describe how to use BlueXP in standard mode. (In addition, restricted mode isn't supported when the Connector is installed on premises.)
.. Click *Let's start*.

.Result

BlueXP is now set up with the Connector that you just installed.

.What's next?

link:task-provide-permissions-on-prem.html[Provide BlueXP with the permissions that you previously setup].