---
sidebar: sidebar
permalink: task-set-up-networking-google.html
keywords: networking, on prem networking, endpoints, urls, ports, ip address, proxy, proxy server, connections
summary: Set up your networking so the Connector can manage resources and processes within your hybrid cloud environment. For example, you need to ensure that connections are available to target networks and that outbound internet access is available.
---

= Set up Google Cloud networking
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Set up your networking so the Connector can manage resources and processes within your hybrid cloud environment. For example, you need to ensure that connections are available to target networks and that outbound internet access is available.

== VPC and subnet 

When you create the Connector, you need to specify the VPC and subnet where the Connector should reside.

== Connections to target networks

A Connector requires a network connection to the location where you're planning to create and manage working environments.

== Outbound internet access

The network location where you deploy the Connector must have an outbound internet connection. Outbound internet access is also required from your web browser when deploying the Connector from the BlueXP console.

=== Endpoints contacted from the BlueXP console

As you use the BlueXP web-based console that's provided through the SaaS layer, it contacts several endpoints to complete data management tasks. This includes endpoints that are contacted to deploy the Connector from the BlueXP console.

link:reference-networking-saas-console.html[View the list of endpoints contacted from the BlueXP console].

=== Endpoints contacted during manual installation

include::_include/endpoints-manual-install.adoc[tag=start]

include::_include/endpoints-manual-install.adoc[tag=update]

=== Endpoints contacted from the Connector

The Connector requires outbound internet access to contact the following endpoints in order to manage resources and processes within your public cloud environment for day-to-day operations.

[cols=2*,options="header,autowidth"]
|===
| Endpoints
| Purpose

| 
\https://www.googleapis.com/compute/v1/
\https://compute.googleapis.com/compute/v1
\https://cloudresourcemanager.googleapis.com/v1/projects
\https://www.googleapis.com/compute/beta
\https://storage.googleapis.com/storage/v1
\https://www.googleapis.com/storage/v1
\https://iam.googleapis.com/v1
\https://cloudkms.googleapis.com/v1
\https://www.googleapis.com/deploymentmanager/v2/projects

| To manage resources in Google Cloud.

| \https://support.netapp.com | To obtain licensing information and to send AutoSupport messages to NetApp support.

a| 

\https://*.api.bluexp.netapp.com

\https://api.bluexp.netapp.com

\https://*.cloudmanager.cloud.netapp.com

\https://cloudmanager.cloud.netapp.com

a| To provide SaaS features and services within BlueXP.

NOTE: The Connector is currently contacting "cloudmanager.cloud.netapp.com" but it will start contacting "api.bluexp.netapp.com" in an upcoming release.

| \https://cloudmanagerinfraprod.azurecr.io

\https://*.blob.core.windows.net
| To upgrade the Connector and its Docker components.

|===

== Proxy server

include::_include/proxy-server.adoc[]

== Ports

include::_include/ports.adoc[]

== IP address limitation

include::_include/ip-limitation.adoc[]