---
sidebar: sidebar
permalink: task-install-connector-azure-marketplace.html
keywords: install connector, azure connector installation, azure connector, install connector in azure, bluexp, create connector, marketplace, azure marketplace
summary: To create a Connector in Azure from the Azure Marketplace, you need to set up your networking, prepare Azure permissions, and then create the Connector.
---

= Create a Connector in Azure from the Azure Marketplace
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
To create a Connector in Azure from the Azure Marketplace, you need to set up your networking, prepare Azure permissions, and then create the Connector.

== Step 1: Set up networking

Ensure that the network location where you plan to install the Connector supports the following requirements. Meeting these requirements enables the Connector to manage resources and processes within your hybrid cloud environment.

Azure region::
If you use Cloud Volumes ONTAP, the Connector should be deployed in the same Azure region as the Cloud Volumes ONTAP systems that it manages, or in the https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies[Azure region pair^] for the Cloud Volumes ONTAP systems. This requirement ensures that an Azure Private Link connection is used between Cloud Volumes ONTAP and its associated storage accounts.
+
https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-enabling-private-link.html[Learn how Cloud Volumes ONTAP uses an Azure Private Link^]

VNet and subnet::
When you create the Connector, you need to specify the VNet and subnet where the Connector should reside.

Connections to target networks::
A Connector requires a network connection to the location where you're planning to create and manage working environments. For example, the VNet where you plan to create Cloud Volumes ONTAP systems or the storage in your on-premises environment.

Outbound internet access::
The network location where you deploy the Connector must have an outbound internet connection to contact specific endpoints, as described in the following sections.

Endpoints contacted from the BlueXP console::
As you use the BlueXP web-based console that's provided through the SaaS layer, it contacts several endpoints to complete data management tasks. This includes endpoints that are contacted to deploy the Connector from the BlueXP console.
+
link:reference-networking-saas-console.html[View the list of endpoints contacted from the BlueXP console].

Endpoints contacted from the Connector::
The Connector requires outbound internet access to contact the following endpoints in order to manage resources and processes within your public cloud environment for day-to-day operations.
+
[cols="2a,1a",options="header,autowidth"]
|===
| Endpoints
| Purpose

include::_include/endpoints-connector.adoc[tag=azure-public-endpoints]

include::_include/endpoints-connector.adoc[tag=azure-china-endpoints]

include::_include/endpoints-connector.adoc[tag=nss-endpoints]

include::_include/endpoints-connector.adoc[tag=saas-endpoints]

include::_include/endpoints-connector.adoc[tag=upgrade-endpoints]

|===

Proxy server::
include::_include/proxy-server.adoc[]

Ports::
include::_include/ports.adoc[]

IP address limitation::
include::_include/ip-limitation.adoc[]

== Step 2: Set up permissions

You can provide permissions in the following ways:

* Option 1: Assign a custom role to the Azure VM using a system-assigned managed identity.

* Option 2: Provide BlueXP with the credentials for an Azure service principal that has the required permissions.

// start tabbed area

[role="tabbed-block"]
====

.Custom role
--
Note that you can create an Azure custom role using the Azure portal, Azure PowerShell, Azure CLI, or REST API. The following steps show how to create the role using the Azure CLI. If you would prefer to use a different method, refer to https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles#steps-to-create-a-custom-role[Azure documentation^]

.Steps 

. If you're planning to manually install the software on your own host, enable a system-assigned managed identity on the VM so that you can provide the required Azure permissions through a custom role. 
+
https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-configure-portal-windows-vm[Microsoft Azure documentation: Configure managed identities for Azure resources on a VM using the Azure portal^]

include::_include/azure-set-up-role.adoc[]

link:task-provide-permissions-azure.html[Learn how to provide these permissions to BlueXP].
--

.Service principal
--
Create and set up a service principal in Azure Active Directory and obtain the Azure credentials that BlueXP needs.

.Create an Azure Active Directory application for role-based access control

include::_include/azure-set-up-service-principal.adoc[tag=app]

.Assign the application to a role
 
include::_include/azure-set-up-service-principal.adoc[tag=role]

.Add Windows Azure Service Management API permissions

include::_include/azure-set-up-service-principal.adoc[tag=api]

.Get the application ID and directory ID for the application

include::_include/azure-set-up-service-principal.adoc[tag=ids]

.Create a client secret

include::_include/azure-set-up-service-principal.adoc[tags=secret]

.Result

Your service principal is now setup and you should have copied the application (client) ID, the directory (tenant) ID, and the value of the client secret. You need to enter this information in BlueXP when you add an Azure account.

link:task-provide-permissions-azure.html[Learn how to provide these permissions to BlueXP].
--

====
// end tabbed area

== Step 3: Create the Connector

Create the Connector directly from the BlueXP web-based console.

.Before you begin

You should have the following:

* An Azure subscription.

* A VNet and subnet in your Azure region of choice.

* Details about a proxy server, if your organization requires a proxy for all outgoing internet traffic:

** IP address
** Credentials
** HTTPS certificate

* An SSH public key, if you want to use that authentication method for the Connector virtual machine. The other option for the authentication method is to use a password. 
+
https://learn.microsoft.com/en-us/azure/virtual-machines/linux-vm-connect?tabs=Linux[Learn about connecting to a Linux VM in Azure^]

* If you don't want BlueXP to automatically create an Azure role for the Connector, then you'll need to create your own link:reference-permissions-azure.html[using the policy on this page].
+
These permissions are for the Connector instance itself. It's a different set of permissions than what you previously set up to deploy the Connector VM.

.Steps

. Go to the NetApp Connector VM page in the Azure Marketplace.
+
https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.netapp-oncommand-cloud-manager[Azure Marketplace page for commercial regions^]

. Select *Get it now* and then select *Continue*.

. From the Azure portal, select *Create* and follow the steps to configure the virtual machine.
+
Note the following as you configure the VM:

* *VM size*: Choose a VM size that meets CPU and RAM requirements. We recommend DS3 v2.

* *Disks*: The Connector can perform optimally with either HDD or SSD disks.

* *Network security group*: The Connector requires inbound connections using SSH, HTTP, and HTTPS.
+
link:reference-ports-azure.html[View security group rules for Azure].

* *Identity*: Under *Management*, select *Enable system assigned managed identity*.
+
This setting is important because a managed identity allows the Connector virtual machine to identify itself to Azure Active Directory without providing any credentials. https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview[Learn more about managed identities for Azure resources^].

. On the *Review + create* page, review your selections and select *Create* to start the deployment.
+
Azure deploys the virtual machine with the specified settings. The virtual machine and Connector software should be running in approximately five minutes.

. Open a web browser from a host that has a connection to the Connector virtual machine and enter the following URL:
+
https://_ipaddress_

. After you log in, set up the Connector:
.. Specify the BlueXP account to associate with the Connector.
.. Enter a name for the system.
.. Under *Are you running in a secured environment?* keep restricted mode disabled.
+
You should keep restricted mode disabled because these steps describe how to use BlueXP in standard mode. You should enable restricted mode only if you have a secure environment and want to disconnect this account from BlueXP backend services. If that's the case, link:task-quick-start-restricted-mode.html[follow steps to get started with BlueXP in restricted mode].
.. Select *Let's start*.

The Connector is now installed and is set up with your BlueXP account.

.What's next?

link:task-provide-permissions-azure.html[Provide BlueXP with the permissions that you previously setup].

== Step 4: Provide permissions to BlueXP

Now that you've created the Connector, you need to provide BlueXP with the permissions that you previously set up. Providing the permissions enables BlueXP to manage your data and storage infrastructure in Azure.

[role="tabbed-block"]
====

.Custom role
--
include::_include/azure-provide-permissions-role.adoc[]

.What's next?

Go to the https://console.bluexp.netapp.com[BlueXP console^] to start using the Connector with BlueXP.
--

.Service principal
--
.Steps

include::_include/azure-provide-permissions-service-principal.adoc[]

.Result

BlueXP now has the permissions that it needs to perform actions in Azure on your behalf.
--

====
// end tabbed area